# Generated by Django 3.0.4 on 2020-03-27 19:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField()),
                ('creationTime', models.DateTimeField()),
                ('info', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
