# Generated by Django 3.0.4 on 2020-03-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20200328_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintable',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
