# Generated by Django 3.0.4 on 2020-03-29 12:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_maintable_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintable',
            name='info',
        ),
        migrations.AddField(
            model_name='maintable',
            name='forTable',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='maintable',
            name='ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
