# Generated by Django 3.0.4 on 2020-03-29 12:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20200329_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='forTable',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
