# Generated by Django 3.0.4 on 2020-03-29 12:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_auto_20200329_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='forTable',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
