# Generated by Django 3.0.4 on 2020-09-16 15:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_auto_20200329_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField()),
                ('creationTime', models.TextField()),
                ('mailCount', models.IntegerField(default=0)),
                ('mailBox', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('mailIds', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='mainTable',
        ),
    ]
